export const EventTypes = {
  ITEM_DETECTED: "ITEM_DETECTED",
  CLASSIFICATION_COMPLETED: "CLASSIFICATION_COMPLETED",
  ROUTE_REQUESTED: "ROUTE_REQUESTED",
  ROUTE_ASSIGNED: "ROUTE_ASSIGNED",
  ROBOT_DISPATCHED: "ROBOT_DISPATCHED",
  ROBOT_ARRIVED: "ROBOT_ARRIVED",
  STOW_STARTED: "STOW_STARTED",
  STOW_COMPLETED: "STOW_COMPLETED",
  STOW_FAILED: "STOW_FAILED",
  INVENTORY_UPDATE_STARTED: "INVENTORY_UPDATE_STARTED",
  INVENTORY_UPDATED: "INVENTORY_UPDATED",
  INVENTORY_MISMATCH: "INVENTORY_MISMATCH"
} as const;
